### ISSUE TITLE
npm found vulnerabilities (Prototype Pollution)

### ISSUE THREAD

**Issue by 3153N** [mongodb-js/query-parser#10]
hey,

npm finds following vulnerability when i try to install the package:

- Prototype Pollution
- Package: lodash
- Patched in: >=4.17.11    
- Dependency of: mongodb-query-parser   
- Path: mongodb-query-parser > mongodb-language-model > lodash 
- More info: https://npmjs.com/advisories/782

regards

**Comment by imlucas** [comment]
closing as this appears to be a burn on use bot account.

**Comment by 3153N** [comment]
the error still exists
